import type Database from "better-sqlite3";
import { MIGRATIONS } from "./migrations";

// Migrations are consumed from the build-time-bundled MIGRATIONS array
// (generated by scripts/gen-migrations.ts from lib/db/migrations/*.sql), not
// read from the filesystem. This keeps runMigrations() working in both Node and
// a Cloudflare Worker, which has no fs/path.
export function runMigrations(db: Database.Database) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS _migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT UNIQUE NOT NULL,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `);

  const applied = new Set(
    db
      .prepare("SELECT name FROM _migrations")
      .all()
      .map((row) => (row as { name: string }).name)
  );

  for (const { name, sql } of MIGRATIONS) {
    if (applied.has(name)) continue;

    db.exec(sql);
    db.prepare("INSERT INTO _migrations (name) VALUES (?)").run(name);
  }
}
