import type Database from "better-sqlite3";
import { runMigrationList } from "./migration-runner";

// Migrations are consumed from the build-time-bundled MIGRATIONS array
// (generated by scripts/gen-migrations.ts from lib/db/migrations/*.sql), not
// read from the filesystem. This keeps runMigrations() working in both Node and
// a Cloudflare Worker, which has no fs/path. The applied-set loop itself lives
// in the shared runner (lib/db/migration-runner.ts); MIGRATIONS is its default
// list, in generated (filename-sorted) order.
export function runMigrations(db: Database.Database) {
  runMigrationList(db);
}
