// Regenerates lib/db/migrations.ts by inlining every .sql file in
// lib/db/migrations/ as a string. This lets runMigrations() consume the
// migrations without touching the filesystem at runtime, so it works in both
// Node (self-hosted) and a Cloudflare Worker (no fs).
//
// Run with: npm run gen:migrations
// The output module is checked in and reviewed; regenerate it whenever a
// migration .sql file is added, removed, or renamed.
import fs from "fs";
import path from "path";

const MIGRATIONS_DIR = path.join(process.cwd(), "lib", "db", "migrations");
const OUT_FILE = path.join(process.cwd(), "lib", "db", "migrations.ts");

const files = fs
  .readdirSync(MIGRATIONS_DIR)
  .filter((f) => f.endsWith(".sql"))
  .sort();

const entries = files
  .map((name) => {
    const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, name), "utf-8");
    // Use a JSON-encoded string literal so any quotes/backslashes/newlines in
    // the SQL are escaped safely and deterministically.
    return `  { name: ${JSON.stringify(name)}, sql: ${JSON.stringify(sql)} },`;
  })
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-migrations.ts — DO NOT EDIT BY HAND.
// Regenerate with: npm run gen:migrations
// Source of truth: lib/db/migrations/*.sql
//
// The .sql files are inlined here as strings so runMigrations() never reads the
// filesystem at runtime — required for the Cloudflare Worker (Durable Object)
// backend, which has no fs. Node and Worker bundlers both see plain ESM here.

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
${entries}
];
`;

fs.writeFileSync(OUT_FILE, out);
console.log(`Wrote ${files.length} migration(s) to ${OUT_FILE}`);
