import Database from "better-sqlite3";
import { useConnection } from "../db";
import { MIGRATIONS, type Migration } from "../db/migrations";
import { runMigrationList } from "../db/migration-runner";
import type { DbBackend } from "./backend";
import type { DurableStore } from "./do-store";

// Blob-based Durable-Object backend — SUPERSEDED on the hosted target by
// DoSqlBackend (do-sql-backend.ts) over the DO's native SQLite. Kept as
// Node-runnable test scaffolding: better-sqlite3 can't load inside workerd, so
// the Repo contract tests (do-backend.test.ts, two-user-isolation.test.ts,
// do-repo-client-batch.test.ts) exercise SqliteRepo over this backend with a
// MemoryDurableStore instead.
//
// Shape: the whole serialised SQLite DB lives as one blob in a DurableStore;
// open() loads it into an in-memory better-sqlite3 connection (routed at getDb()
// via useConnection so the delegated lib/db/* functions run unchanged), and
// persist() serialises (`db.serialize()`) the connection back. Zero auth
// knowledge — isolation is whoever hands it a store.

export { MemoryDurableStore } from "./do-store";
export type { DurableStore } from "./do-store";

// --- Bundled migrations (Worker-safe) --------------------------------------
//
// lib/db/migrate.ts reads .sql files from disk via fs, which cannot work inside
// a Cloudflare Worker / Durable Object — there is no filesystem. lib/db/migrations.ts
// inlines those same .sql files as `MIGRATIONS` strings (regenerated by
// `npm run gen:migrations`), so we consume that here instead of a local copy.

// Idempotent, name-ordered migration runner over the bundled SQL strings — the
// Worker-safe equivalent of lib/db/migrate.ts's runMigrations(). Thin wrapper
// over the shared runner (lib/db/migration-runner.ts); unlike the other callers
// it sorts by name first — historical behavior of this export, kept because
// scripts/seed-demo.ts and do-backend.test.ts consume it directly (a no-op for
// the generated MIGRATIONS list, which is already filename-sorted).
export function runMigrationsFromStrings(
  db: Database.Database,
  migrations: readonly Migration[] = MIGRATIONS
): void {
  runMigrationList(db, [...migrations].sort((a, b) => a.name.localeCompare(b.name)));
}

export class DoBackend implements DbBackend {
  private db: Database.Database | null = null;

  constructor(private store: DurableStore) {}

  async open(): Promise<Database.Database> {
    // Re-assert this DO's connection as the active one on EVERY open(), not just
    // the first. useConnection() is a process-global override (one connection at
    // a time — the correct model for one Durable Object per isolate). In a real
    // DO that's naturally per-instance; but when several DoBackends coexist in
    // one process (the in-process multi-user tests; any future multi-DO host),
    // each operation must re-point the global at its own DB or a second user's
    // backend would shadow the first. Cheap and idempotent.
    if (this.db) {
      useConnection(this.db);
      return this.db;
    }

    const blob = await this.store.get();
    const db = blob
      ? new Database(Buffer.from(blob)) // load persisted DB → in-memory connection
      : new Database(); // first access for this DO: fresh in-memory DB

    db.pragma("foreign_keys = ON");
    // Run schema migrations at first access. Idempotent: builds the schema on a
    // fresh DB, no-op on an already-migrated one.
    runMigrationsFromStrings(db);

    useConnection(db);
    this.db = db;
    return db;
  }

  async persist(db: Database.Database): Promise<void> {
    await this.store.put(new Uint8Array(db.serialize()));
  }

  async close(): Promise<void> {
    useConnection(null);
    this.db?.close();
    this.db = null;
  }
}
