import Database from "better-sqlite3";
import { useConnection } from "../db";
import { MIGRATIONS, type Migration } from "../db/migrations";
import type { DbBackend } from "./backend";
import type { DurableStore } from "./do-store";

// Durable-Object-per-user backend (hosted target). One DO instance == one user's
// SQLite database. The whole serialised SQLite DB lives at rest as a single blob
// in the Durable Object's storage (which is itself SQLite-backed and durable);
// on open() that blob is loaded into an in-memory better-sqlite3 connection that
// every query runs against, and on persist() the connection is serialised
// (`db.serialize()`) and written back to DO storage.
//
// This mirrors EncryptedBlobBackend's shape exactly — read whole-DB blob → open
// in-memory connection → route getDb() at it (useConnection) so SqliteRepo's
// delegated lib/db/* functions operate on it transparently → serialise back on
// persist() — but swaps the BlobStore-with-crypto for a DurableStore over the
// DO's own storage. SqliteRepo sits on top unchanged.
//
// This backend has ZERO auth knowledge: it does not know which user it serves.
// The DO is already addressed by id by the time this runs; routing the request
// to the correct DO (and therefore the correct user's database) is Session 6's
// job, not this file's.
//
// Note (batching, inherited from SqliteRepo): persist() serialises + writes the
// whole DB, so a write loop pays that cost per row. The same insertMany()/
// write-boundary follow-up tracked for EncryptedBlobBackend applies here.

// The blob store + its DO-backed and in-memory implementations live in do-store.ts
// (no better-sqlite3 dependency) so they can be bundled into a Worker. Re-exported
// here so callers can import everything from "./do-backend".
export {
  DurableObjectStore,
  MemoryDurableStore,
  CHUNK_BYTES,
} from "./do-store";
export type { DurableStore, DurableStorageLike } from "./do-store";

// --- Bundled migrations (Worker-safe) --------------------------------------
//
// lib/db/migrate.ts reads .sql files from disk via fs, which cannot work inside
// a Cloudflare Worker / Durable Object — there is no filesystem. Session 4's
// lib/db/migrations.ts inlines those same .sql files as `MIGRATIONS` strings
// (regenerated by `npm run gen:migrations`), so we consume that here instead of
// a local copy. `BundledMigration` and `BUNDLED_MIGRATIONS` remain as aliases so
// existing imports keep working.
export type BundledMigration = Migration;
export const BUNDLED_MIGRATIONS: readonly BundledMigration[] = MIGRATIONS;

// Idempotent, name-ordered migration runner over the bundled SQL strings — the
// Worker-safe equivalent of lib/db/migrate.ts's fs-based runMigrations().
export function runMigrationsFromStrings(
  db: Database.Database,
  migrations: readonly BundledMigration[] = BUNDLED_MIGRATIONS
): void {
  db.exec(`
    CREATE TABLE IF NOT EXISTS _migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT UNIQUE NOT NULL,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `);

  const applied = new Set(
    db
      .prepare("SELECT name FROM _migrations")
      .all()
      .map((row) => (row as { name: string }).name)
  );

  const ordered = [...migrations].sort((a, b) => a.name.localeCompare(b.name));
  for (const { name, sql } of ordered) {
    if (applied.has(name)) continue;
    db.exec(sql);
    db.prepare("INSERT INTO _migrations (name) VALUES (?)").run(name);
  }
}

export class DoBackend implements DbBackend {
  private db: Database.Database | null = null;

  constructor(private store: DurableStore) {}

  async open(): Promise<Database.Database> {
    // Re-assert this DO's connection as the active one on EVERY open(), not just
    // the first. useConnection() is a process-global override (one connection at
    // a time — the correct model for one Durable Object per isolate). In a real
    // DO that's naturally per-instance; but when several DoBackends coexist in
    // one process (the in-process multi-user tests; any future multi-DO host),
    // each operation must re-point the global at its own DB or a second user's
    // backend would shadow the first. Cheap and idempotent.
    if (this.db) {
      useConnection(this.db);
      return this.db;
    }

    const blob = await this.store.get();
    const db = blob
      ? new Database(Buffer.from(blob)) // load persisted DB → in-memory connection
      : new Database(); // first access for this DO: fresh in-memory DB

    db.pragma("foreign_keys = ON");
    // Run schema migrations at first access. Idempotent: builds the schema on a
    // fresh DB, no-op on an already-migrated one.
    runMigrationsFromStrings(db);

    useConnection(db);
    this.db = db;
    return db;
  }

  async persist(db: Database.Database): Promise<void> {
    await this.store.put(new Uint8Array(db.serialize()));
  }

  async close(): Promise<void> {
    useConnection(null);
    this.db?.close();
    this.db = null;
  }
}
